name: CI

on:
  push:
    branches:
      - master
      - main
      - develop
      - "feature/**"
  pull_request:
    branches:
      - master
      - main
      - develop

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build
        run: mvn -B -U clean package

      - name: Test
        run: mvn -B -U test